#############################################################################
# Makefile for building: CIS467Project
# Generated by qmake (2.01a) (Qt 4.7.0) on: Mon Oct 18 01:58:59 2010
# Project:  CIS467Project.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile CIS467Project.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -Igui -Igenerator -Imodels -I/usr/X11R6/include -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -L/usr/X11R6/lib -lQtSvg -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gui/gui.cpp \
		gui/main.cpp \
		gui/cell.cpp \
		generator/generator.cpp \
		models/maze.cpp \
		gui/graphicsview.cpp moc_gui.cpp \
		moc_generator.cpp \
		moc_maze.cpp \
		moc_graphicsview.cpp
OBJECTS       = gui.o \
		main.o \
		cell.o \
		generator.o \
		maze.o \
		graphicsview.o \
		moc_gui.o \
		moc_generator.o \
		moc_maze.o \
		moc_graphicsview.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		CIS467Project.pro
QMAKE_TARGET  = CIS467Project
DESTDIR       = 
TARGET        = CIS467Project

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_gui.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CIS467Project.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtOpenGL.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile CIS467Project.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtOpenGL.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile CIS467Project.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/CIS467Project1.0.0 || $(MKDIR) .tmp/CIS467Project1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/CIS467Project1.0.0/ && $(COPY_FILE) --parents ui_mainwindow.h gui/gui.h gui/cell.h generator/generator.h models/maze.h gui/graphicsview.h .tmp/CIS467Project1.0.0/ && $(COPY_FILE) --parents gui/gui.cpp gui/main.cpp gui/cell.cpp generator/generator.cpp models/maze.cpp gui/graphicsview.cpp .tmp/CIS467Project1.0.0/ && $(COPY_FILE) --parents gui/gui.ui .tmp/CIS467Project1.0.0/ && (cd `dirname .tmp/CIS467Project1.0.0` && $(TAR) CIS467Project1.0.0.tar CIS467Project1.0.0 && $(COMPRESS) CIS467Project1.0.0.tar) && $(MOVE) `dirname .tmp/CIS467Project1.0.0`/CIS467Project1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/CIS467Project1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_gui.cpp moc_generator.cpp moc_maze.cpp moc_graphicsview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gui.cpp moc_generator.cpp moc_maze.cpp moc_graphicsview.cpp
moc_gui.cpp: models/maze.h \
		generator/generator.h \
		gui/graphicsview.h \
		gui/gui.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/gui.h -o moc_gui.cpp

moc_generator.cpp: models/maze.h \
		generator/generator.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) generator/generator.h -o moc_generator.cpp

moc_maze.cpp: models/maze.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) models/maze.h -o moc_maze.cpp

moc_graphicsview.cpp: gui/graphicsview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) gui/graphicsview.h -o moc_graphicsview.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_gui.h
compiler_uic_clean:
	-$(DEL_FILE) ui_gui.h
ui_gui.h: gui/gui.ui
	/usr/bin/uic-qt4 gui/gui.ui -o ui_gui.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

gui.o: gui/gui.cpp gui/gui.h \
		models/maze.h \
		generator/generator.h \
		gui/graphicsview.h \
		ui_gui.h \
		gui/cell.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gui.o gui/gui.cpp

main.o: gui/main.cpp gui/gui.h \
		models/maze.h \
		generator/generator.h \
		gui/graphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o gui/main.cpp

cell.o: gui/cell.cpp gui/cell.h \
		models/maze.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cell.o gui/cell.cpp

generator.o: generator/generator.cpp generator/generator.h \
		models/maze.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o generator.o generator/generator.cpp

maze.o: models/maze.cpp models/maze.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o maze.o models/maze.cpp

graphicsview.o: gui/graphicsview.cpp gui/graphicsview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o graphicsview.o gui/graphicsview.cpp

moc_gui.o: moc_gui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gui.o moc_gui.cpp

moc_generator.o: moc_generator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_generator.o moc_generator.cpp

moc_maze.o: moc_maze.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_maze.o moc_maze.cpp

moc_graphicsview.o: moc_graphicsview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_graphicsview.o moc_graphicsview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

